### ISSUE TITLE
Текст наезжает на картинку

### ISSUE THREAD

**Issue by kos-vkg** [netology-code/git-homeworks-neuro-fork#34]
пользователь @solarrust
Описание проблемы
Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение
Шаги по воспроизведению

Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

Ожидаемый результат

Текст не наезжает на изображение
Фактический результат

Текст наезжает на изображение (см. скриншот)

![skr1](https://user-images.githubusercontent.com/73792290/98352297-e2c3cf80-202e-11eb-886a-670c874d5a7f.png)

Программное окружение

Устройство: iPhone 8+ (iOS 12.1)
Браузер: Chrome (70.0.3538.75)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
