### ISSUE TITLE
Форма обратной связи слишком сжата

### ISSUE THREAD

**Issue by kos-vkg** [netology-code/git-homeworks-neuro-fork#35]
пользователь @solarrust.
Описание проблемы

Форма обратной связи слишком сжата по вертикали.
Шаги по воспроизведению
    Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome
    нажать кн. Обратная связь
Ожидаемый результат

Появляется форма обратной связи размером во весь экран. 
Фактический результат

Форма обратной связи слишком сжата по вертикали.  (см. скриншот)
![skr2](https://user-images.githubusercontent.com/73792290/98354649-13f1cf00-2032-11eb-920c-7c4e3b075f71.png)

Программное окружение

    Устройство: iPhone 8+ (iOS 12.1)
    Браузер: Chrome (70.0.3538.75)

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
