### ISSUE TITLE
index.html: title overlaps an image (mobile)

### ISSUE THREAD

**Issue by supernovaw** [netology-code/git-homeworks-neuro-fork#7]
Occurs when viewing on a phone, making the text unreadable
iPhone 8+, iOS 12.1, Chrome 70.0.3538.75

![68747470733a2f2f692e696d6775722e636f6d2f3268635436784d2e706e67](https://user-images.githubusercontent.com/55014094/69715520-2130e900-1154-11ea-8f12-57e6916fa14b.png)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
