### ISSUE TITLE
index.html: callback menu is too shrinked (mobile)

### ISSUE THREAD

**Issue by supernovaw** [netology-code/git-homeworks-neuro-fork#8]
Occurs when viewing on a phone, making design disproportional
iPhone 8+, iOS 12.1, Chrome 70.0.3538.75

![68747470733a2f2f692e696d6775722e636f6d2f48635370596b542e706e67](https://user-images.githubusercontent.com/55014094/69715825-a6b49900-1154-11ea-8e0e-e3cc2a6977a8.png)

@solarrust

**Comment by solarrust** [comment]
Great! Thanks, someday I'll fix it =)
